package controle.venda.views;

import controle.venda.dao.ClienteDao;
import controle.venda.model.Cliente;
import java.awt.AWTKeyStroke;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.KeyboardFocusManager;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture;
import utilitarios.UpperCaseDocument;

/**
 *
 * @author frede
 */
public class CadastroClientes extends javax.swing.JDialog {

    /**
     * Creates new form CadastroCliente
     */
    
    private ClienteDao clienteDao;
    private ArrayList<Cliente> lista;
    private int posicao_atual = -1;
    private Cliente clienteSelecionado;
    private Cliente clienteAlterar;
    
    
    private DaemonThread myThread = null;
    int count = 0;
    VideoCapture webSource = null;

    Mat frame = new Mat();
    MatOfByte mem = new MatOfByte();

    /**
     * Creates new form Snapshot
     */
    class DaemonThread implements Runnable {

        protected volatile boolean runnable = false;

        @Override
        public void run() {
            synchronized (this) {
                while (runnable) {
                    if (webSource.grab()) {
                        try {
                            webSource.retrieve(frame);
                            Highgui.imencode(".bmp", frame, mem);
                            //Highgui.imencode(".png", frame, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));

                            BufferedImage buff = (BufferedImage) im;
                            Graphics g = jPanel1.getGraphics();

                            if (g.drawImage(buff, 0, 0, getWidth(), getHeight() - 150, 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                                if (runnable == false) {
                                    System.out.println("Going to wait()");
                                    this.wait();
                                }
                            }
                        } catch (Exception ex) {
                           // System.out.println("Error" + ex.getMessage());
                        }
                    }
                }
            }
        }
    }

    public CadastroClientes() {

        this.clienteDao = new ClienteDao();
        this.clienteSelecionado = new Cliente();
        this.clienteAlterar = clienteSelecionado;

        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        this.jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        btnPrimeiro.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnProximo.setEnabled(false);
        btnUltimo.setEnabled(false);

        jTable1.setEnabled(false);

        // Desabilita a Segunda Aba
        tabClientes.setEnabledAt(1, false);
        
        // Desabilita a Terceira Aba
        tabClientes.setEnabledAt(2, false);
        
        // Deixa a Primeira Aba Selecionada
        tabClientes.setSelectedIndex(0);
        txfCpf.requestFocus();

        // Colocando enter para pular de campo 
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        /*     
        Insets in = Toolkit.getDefaultToolkit().getScreenInsets(this.getGraphicsConfiguration());
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int width = d.width - (in.left + in.top);
        int height = d.height - (in.top + in.bottom);
        this.setLocation(0, 0);
        this.setSize(width, height);
         */
        setResizable(false);
        this.addComponentListener(new ComponentAdapter() {
            public void componentMoved(ComponentEvent e) {
                setEnabled(false);
                setEnabled(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblCadastroClientes = new javax.swing.JLabel();
        tabClientes = new javax.swing.JTabbedPane();
        abaPesquisa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonListar = new javax.swing.JButton();
        jButtonNovoCliente = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfPesquisar = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        abaDadosPessoais = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        txfCpf = new javax.swing.JTextField();
        txfNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnFoto = new javax.swing.JButton();
        abaFoto = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        btnTirarFoto = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        pnlImagem = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Vendas");

        lblCadastroClientes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblCadastroClientes.setForeground(new java.awt.Color(255, 0, 0));
        lblCadastroClientes.setText("CADASTRO DE CLIENTES");

        tabClientes.setForeground(new java.awt.Color(0, 0, 255));
        tabClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClientesMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes "));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "NOME"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jButtonNovoCliente.setText("Novo");
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonListar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNovoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFechar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrimeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUltimo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrimeiro)
                        .addComponent(btnAnterior)
                        .addComponent(btnProximo)
                        .addComponent(btnUltimo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonListar)
                        .addComponent(jButtonNovoCliente)
                        .addComponent(btnFechar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabClientes.addTab("Pesquisa", abaPesquisa);

        lblCpf.setText("CPF:");

        lblNome.setText("Nome:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/venda/imagens/webcam.png"))); // NOI18N
        btnFoto.setText("Tirar Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaDadosPessoaisLayout = new javax.swing.GroupLayout(abaDadosPessoais);
        abaDadosPessoais.setLayout(abaDadosPessoaisLayout);
        abaDadosPessoaisLayout.setHorizontalGroup(
            abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDadosPessoaisLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfNome)))
                    .addGroup(abaDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFoto)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        abaDadosPessoaisLayout.setVerticalGroup(
            abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnVoltar)
                    .addComponent(btnFoto))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        tabClientes.addTab("Dados Pessoais", abaDadosPessoais);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnParar.setText("Parar");

        btnTirarFoto.setText("Tirar Foto");
        btnTirarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarFotoActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlImagemLayout = new javax.swing.GroupLayout(pnlImagem);
        pnlImagem.setLayout(pnlImagemLayout);
        pnlImagemLayout.setHorizontalGroup(
            pnlImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        pnlImagemLayout.setVerticalGroup(
            pnlImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout abaFotoLayout = new javax.swing.GroupLayout(abaFoto);
        abaFoto.setLayout(abaFotoLayout);
        abaFotoLayout.setHorizontalGroup(
            abaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaFotoLayout.createSequentialGroup()
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTirarFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addComponent(pnlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        abaFotoLayout.setVerticalGroup(
            abaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaFotoLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(pnlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(abaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnParar)
                    .addComponent(btnTirarFoto)
                    .addComponent(btnSair)))
        );

        tabClientes.addTab("Tirar Foto", abaFoto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lblCadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastroClientes)
                .addGap(18, 18, 18)
                .addComponent(tabClientes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txfCpf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O cpf não pode ser vazio");
            txfCpf.requestFocus();
            return;
        }

        if (txfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O nome não pode ser vazio");
            txfNome.requestFocus();
            return;
        }

        try {
            Cliente cliente = new Cliente();
            cliente.setCpf(txfCpf.getText());
            cliente.setNome(txfNome.getText());
            //RepositorioCliente.obterInstancia().inserir(cliente);
            this.clienteDao.insert(cliente);
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txfPesquisar.setText("");

        btnPrimeiro.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnProximo.setEnabled(false);
        btnUltimo.setEnabled(false);

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        // Habilita a Primeira Aba
        tabClientes.setEnabledAt(0, true);

        // Desabilita a Segunda Aba
        tabClientes.setEnabledAt(1, false);

        // Deixa a Primeira Aba Selecionada
        tabClientes.setSelectedIndex(0);


    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tabClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClientesMouseClicked
        txfCpf.requestFocus();
    }//GEN-LAST:event_tabClientesMouseClicked

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        btnPrimeiro.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnProximo.setEnabled(true);
        btnUltimo.setEnabled(true);

        jTable1.setEnabled(true);

        try {
            DefaultTableModel modelo = new DefaultTableModel() {
                public boolean isCellEditable(int linha, int coluna) {
                    return false;// retornando false para o usuario nao poder editar nada na tabela
                }
            };
            modelo.setColumnIdentifiers(new String[]{"CPF", "NOME"});

            this.lista = this.clienteDao.selectAll();

            for (int i = 0; i < lista.size(); i++) {
                modelo.addRow(new Object[]{this.lista.get(i).getCpf(), this.lista.get(i).getNome()});
            }
            jTable1.setModel(modelo);

        } catch (SQLException ex) {
            // Logger.getLogger(FormConsultaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
        tabClientes.setEnabledAt(1, true);
        tabClientes.setEnabledAt(0, false);
        tabClientes.setSelectedIndex(1);
        
        txfNome.setDocument(new UpperCaseDocument());
        txfCpf.setText("");
        txfNome.setText("");
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Habilita a Primeira Aba
        tabClientes.setEnabledAt(0, true);

        // Desabilita a Segunda Aba
        tabClientes.setEnabledAt(1, false);

        // Deixa a Primeira Aba Selecionada
        tabClientes.setSelectedIndex(0);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedRow() == -1) {
            return;
        }

        // Duplo Clique    
        if (evt.getClickCount() > 1) {
            // JOptionPane.showMessageDialog(null, "Clicou duas vezes");
            btnSalvar.setEnabled(false);

            // Habilita a Segunda Aba
            tabClientes.setEnabledAt(1, true);

            // Desabilita a Primeira Aba
            tabClientes.setEnabledAt(0, false);

            // Deixa a Segunda Aba Selecionada
            tabClientes.setSelectedIndex(1);

            txfCpf.setEnabled(false);
            txfNome.requestFocus();
        }
        mostrarDadoSelecionadoTabela();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        posicao_atual = 0;

        if (posicao_atual == 0) {
            btnPrimeiro.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnProximo.setEnabled(true);
            btnUltimo.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Já está no primeiro registro!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

        try {
            this.clienteSelecionado = this.alteraPosicao(this.posicao_atual);

            if (this.clienteSelecionado != null) {
                this.jTable1.setRowSelectionInterval(this.posicao_atual, this.posicao_atual);
                // this.alteraImagem(this.clienteSelecionado);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        mostrarDadoSelecionadoTabela();
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        btnProximo.setEnabled(true);
        btnUltimo.setEnabled(true);

        try {
            this.clienteSelecionado = this.alteraPosicao(--this.posicao_atual);

            if (this.clienteSelecionado != null) {
                this.jTable1.setRowSelectionInterval(this.posicao_atual, this.posicao_atual);
                //  this.alteraImagem(this.clienteSelecionado);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        mostrarDadoSelecionadoTabela();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * Button Next
     *
     * @param evt
     */
    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        btnAnterior.setEnabled(true);
        btnPrimeiro.setEnabled(true);
        try {
            this.clienteSelecionado = this.alteraPosicao(++this.posicao_atual);

            if (this.clienteSelecionado != null) {
                // System.out.println("Posição: " + this.posicao_atual);
                this.jTable1.setRowSelectionInterval(this.posicao_atual, this.posicao_atual);
                // this.alteraImagem(this.clienteSelecionado);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        mostrarDadoSelecionadoTabela();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        posicao_atual = lista.size() - 1;

        if (posicao_atual == posicao_atual) {
            btnProximo.setEnabled(false);
            btnUltimo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Já está no último registro!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

        try {
            this.clienteSelecionado = this.alteraPosicao(this.posicao_atual);

            if (this.clienteSelecionado != null) {
                this.jTable1.setRowSelectionInterval(this.posicao_atual, this.posicao_atual);
                // this.alteraImagem(this.clienteSelecionado);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        mostrarDadoSelecionadoTabela();

    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed

        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int linha, int coluna) {
                return false;// retornando false para o usuario nao poder editar nada na tabela
            }
        };

        modelo.setColumnIdentifiers(new String[]{"CPF", "Nome"});

        try {
            String pesquisa = this.txfPesquisar.getText();

            lista = this.clienteDao.search(pesquisa);

            for (int i = 0; i < lista.size(); i++) {
                Cliente cliente = lista.get(i);
                modelo.addRow(new Object[]{cliente.getCpf(), cliente.getNome()});
            }

            jTable1.setModel(modelo);

        } catch (SQLException ex) {
            // Logger.getLogger(FormConsultaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Cliente cliente = this.lista.get(jTable1.getSelectedRow());

        // mostra a showOptionDialog
        int choice = JOptionPane.showOptionDialog(null,
                "Deseja realmente excluir o cliente " + cliente.getNome() + "?",
                "Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, null, null);

        // Botão SIM
        if (choice == JOptionPane.YES_OPTION) {
            try {
                this.clienteDao.remove(cliente.getCpf());
                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o Cliente! Possui venda cadastrada.");
                //JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        // Botão NÃO    
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       
        Cliente cliente = this.lista.get(jTable1.getSelectedRow());

        // mostra a showOptionDialog
        int choice = JOptionPane.showOptionDialog(null,
                "Deseja realmente alterar o cliente " + cliente.getNome() + "?",
                "Alteração",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, null, null);

        // Botão SIM
        if (choice == JOptionPane.YES_OPTION) {
        try {
            clienteAlterar.setCpf(txfCpf.getText());
            clienteAlterar.setNome(txfNome.getText());
            this.clienteDao.update(clienteAlterar);
            JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        // Botão NÃO    
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        if(txfNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome antes de prosseguir!");  
        }else{
            //iniciarWebCam();
            Cliente cliente = new Cliente();
            cliente.setNome(txfNome.getText());
            setTitle("Foto do Cliente: " + txfNome.getText());
            // Habilita a Terceira Aba
            tabClientes.setEnabledAt(2, true);
        
            // Desabilita a Segunda Aba
            tabClientes.setEnabledAt(1, false);
            
            // Deixa a Terceira Aba Selecionada
            tabClientes.setSelectedIndex(2);
        } 
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        iniciarWebCam();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnTirarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirarFotoActionPerformed
        int returnVal = jFileChooser1.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            Highgui.imwrite(file.getPath()+".jpg", frame);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btnTirarFotoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        //setTitle("Controle de Vendas");
        iniciarWebCam();
        pararWebCam();
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    public Cliente alteraPosicao(int proximaPosicao) throws SQLException, Exception {

        int totalRegistros = this.lista.size();

        if (proximaPosicao >= 0 && proximaPosicao < totalRegistros) {
            return this.lista.get(proximaPosicao);
        }

        if (proximaPosicao < 0) {
            // throw new Exception("Não já registro anterior!");
            JOptionPane.showMessageDialog(null, "Não há registro anterior!", "Alerta", JOptionPane.WARNING_MESSAGE);
            btnPrimeiro.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnProximo.setEnabled(true);
            btnUltimo.setEnabled(true);
        }

        if (proximaPosicao >= totalRegistros) {
            //throw new Exception("Não há proximo registro!");
            JOptionPane.showMessageDialog(null, "Não há proximo registro!", "Alerta", JOptionPane.WARNING_MESSAGE);
            btnProximo.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnAnterior.setEnabled(true);
            btnPrimeiro.setEnabled(true);
        }

        return null;
    }

    private void mostrarDadoSelecionadoTabela() {
        int index = this.jTable1.getSelectedRow();

        this.clienteSelecionado = this.lista.get(index);
        this.posicao_atual = index;

        if (jTable1.getSelectedRow() != -1) {

            this.clienteSelecionado = this.lista.get(jTable1.getSelectedRow());
            txfCpf.setText(clienteSelecionado.getCpf());
            txfNome.setText(clienteSelecionado.getNome());
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma registro!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void iniciarWebCam(){
        webSource = new VideoCapture(0);
        myThread = new CadastroClientes.DaemonThread();
        Thread t = new Thread(myThread);
        t.setDaemon(true);
        myThread.runnable = true;
        t.start();
        btnIniciar.setEnabled(false);  //botão Iniciar
        btnParar.setEnabled(true);  // botão Parar
    }
    
    public void pararWebCam(){
        myThread.runnable = false;
        btnParar.setEnabled(false);
        btnIniciar.setEnabled(true);

        webSource.release();
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaDadosPessoais;
    private javax.swing.JPanel abaFoto;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTirarFoto;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCadastroClientes;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlImagem;
    private javax.swing.JTabbedPane tabClientes;
    private javax.swing.JTextField txfCpf;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfPesquisar;
    // End of variables declaration//GEN-END:variables

}
